Object.assign(process.env, {
  NODE_ENV: 'test',
  APP_NAME: 'Katla test',
  PORT: '3001',
  BASE_URL_PREFIX: '/api',
  API_BASE_URL: 'http://localhost:3001',
  CLIENT_KEY: 'test-client-key',
  CLIENT_SECRET: 'test-client-secret',
  SAML_CALLBACK_URL: 'http://localhost:3001/api/saml/login/callback',
  SAML_LOGOUT_CALLBACK_URL: 'http://localhost:3001/api/saml/logout/callback',
  SAML_FAILURE_REDIRECT: 'http://localhost:3000/login',
  SAML_SUCCESS_REDIRECT: 'http://localhost:3000',
  SAML_ENTRY_SSO: 'http://localhost:4000/sso',
  SAML_IDP_PUBLIC_CERT: 'test-certificate',
  SAML_ISSUER: 'test-issuer',
  SAML_PRIVATE_KEY: 'test-private-key',
  SAML_PUBLIC_KEY: 'test-public-key',
  SECRET_KEY: 'test-secret-key',
  LOG_FORMAT: 'dev',
  LOG_DIR: '../../data/test-logs',
  ORIGIN: 'http://localhost:3000',
  CREDENTIALS: 'true',
  SESSION_MEMORY: 'true',
  SWAGGER_ENABLED: 'false',
  MUNICIPALITY_ID: '2281',
  NAMESPACE: 'test',
});
